import type { Migration } from './index'

const NOW = `(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`

/**
 * MVP schema. Conventions:
 * - Primary keys are UUID text generated by the app (stable across a future sync).
 * - Money columns end in `_minor` and hold integer hundredths.
 * - Calendar dates are `YYYY-MM-DD`, times `HH:MM`, timestamps ISO-8601 UTC.
 * - Balances and totals are derived with queries, never stored.
 */
export const migration001: Migration = {
  version: 1,
  name: 'initial schema',
  statements: [
    `CREATE TABLE semesters (
      id TEXT PRIMARY KEY NOT NULL,
      name TEXT NOT NULL CHECK (length(trim(name)) > 0),
      academic_year TEXT,
      start_date TEXT,
      end_date TEXT,
      created_at TEXT NOT NULL DEFAULT ${NOW},
      updated_at TEXT NOT NULL DEFAULT ${NOW}
    )`,

    `CREATE TABLE settings (
      id INTEGER PRIMARY KEY CHECK (id = 1),
      student_name TEXT NOT NULL CHECK (length(trim(student_name)) > 0),
      school_name TEXT,
      currency TEXT NOT NULL DEFAULT 'PHP',
      spending_days TEXT NOT NULL DEFAULT '0123456',
      current_semester_id TEXT REFERENCES semesters(id) ON DELETE SET NULL,
      onboarded_at TEXT,
      created_at TEXT NOT NULL DEFAULT ${NOW},
      updated_at TEXT NOT NULL DEFAULT ${NOW}
    )`,

    `CREATE TABLE subjects (
      id TEXT PRIMARY KEY NOT NULL,
      semester_id TEXT NOT NULL REFERENCES semesters(id) ON DELETE RESTRICT,
      name TEXT NOT NULL CHECK (length(trim(name)) > 0),
      code TEXT,
      instructor TEXT,
      room TEXT,
      color TEXT NOT NULL,
      notes TEXT,
      archived_at TEXT,
      created_at TEXT NOT NULL DEFAULT ${NOW},
      updated_at TEXT NOT NULL DEFAULT ${NOW}
    )`,
    `CREATE UNIQUE INDEX ux_subjects_semester_name
      ON subjects (semester_id, name COLLATE NOCASE) WHERE archived_at IS NULL`,

    `CREATE TABLE class_schedules (
      id TEXT PRIMARY KEY NOT NULL,
      subject_id TEXT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
      day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
      start_time TEXT NOT NULL,
      end_time TEXT NOT NULL,
      room TEXT,
      created_at TEXT NOT NULL DEFAULT ${NOW},
      updated_at TEXT NOT NULL DEFAULT ${NOW},
      CHECK (end_time > start_time),
      UNIQUE (subject_id, day_of_week, start_time)
    )`,
    `CREATE INDEX ix_class_schedules_day ON class_schedules (day_of_week, start_time)`,

    `CREATE TABLE tasks (
      id TEXT PRIMARY KEY NOT NULL,
      subject_id TEXT REFERENCES subjects(id) ON DELETE SET NULL,
      title TEXT NOT NULL CHECK (length(trim(title)) > 0),
      description TEXT,
      kind TEXT NOT NULL DEFAULT 'assignment'
        CHECK (kind IN ('assignment', 'project', 'homework', 'study', 'personal')),
      due_date TEXT,
      due_time TEXT,
      priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high')),
      status TEXT NOT NULL DEFAULT 'todo' CHECK (status IN ('todo', 'in_progress', 'completed')),
      completed_at TEXT,
      created_at TEXT NOT NULL DEFAULT ${NOW},
      updated_at TEXT NOT NULL DEFAULT ${NOW},
      CHECK (due_time IS NULL OR due_date IS NOT NULL)
    )`,
    `CREATE INDEX ix_tasks_status_due ON tasks (status, due_date)`,
    `CREATE INDEX ix_tasks_subject ON tasks (subject_id)`,

    `CREATE TABLE exams (
      id TEXT PRIMARY KEY NOT NULL,
      subject_id TEXT REFERENCES subjects(id) ON DELETE SET NULL,
      title TEXT NOT NULL CHECK (length(trim(title)) > 0),
      kind TEXT NOT NULL DEFAULT 'exam' CHECK (kind IN ('exam', 'quiz', 'presentation', 'project')),
      exam_date TEXT NOT NULL,
      exam_time TEXT,
      coverage TEXT,
      notes TEXT,
      study_status TEXT NOT NULL DEFAULT 'not_started'
        CHECK (study_status IN ('not_started', 'studying', 'ready', 'completed')),
      created_at TEXT NOT NULL DEFAULT ${NOW},
      updated_at TEXT NOT NULL DEFAULT ${NOW}
    )`,
    `CREATE INDEX ix_exams_date ON exams (exam_date)`,
    `CREATE INDEX ix_exams_subject ON exams (subject_id)`,

    `CREATE TABLE savings_goals (
      id TEXT PRIMARY KEY NOT NULL,
      name TEXT NOT NULL CHECK (length(trim(name)) > 0),
      target_minor INTEGER NOT NULL CHECK (target_minor > 0),
      target_date TEXT,
      archived_at TEXT,
      created_at TEXT NOT NULL DEFAULT ${NOW},
      updated_at TEXT NOT NULL DEFAULT ${NOW}
    )`,

    `CREATE TABLE allowance_plans (
      id TEXT PRIMARY KEY NOT NULL,
      amount_minor INTEGER NOT NULL CHECK (amount_minor > 0),
      frequency TEXT NOT NULL CHECK (frequency IN ('daily', 'weekly', 'biweekly', 'monthly', 'custom')),
      interval_days INTEGER CHECK (interval_days IS NULL OR interval_days BETWEEN 1 AND 366),
      anchor_date TEXT NOT NULL,
      savings_minor INTEGER NOT NULL DEFAULT 0 CHECK (savings_minor >= 0),
      savings_goal_id TEXT REFERENCES savings_goals(id) ON DELETE SET NULL,
      effective_from TEXT NOT NULL,
      is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
      created_at TEXT NOT NULL DEFAULT ${NOW},
      updated_at TEXT NOT NULL DEFAULT ${NOW},
      CHECK (savings_minor <= amount_minor),
      CHECK (frequency <> 'custom' OR interval_days IS NOT NULL)
    )`,
    `CREATE UNIQUE INDEX ux_allowance_plans_active ON allowance_plans (is_active) WHERE is_active = 1`,

    `CREATE TABLE allowances (
      id TEXT PRIMARY KEY NOT NULL,
      plan_id TEXT REFERENCES allowance_plans(id) ON DELETE SET NULL,
      kind TEXT NOT NULL CHECK (kind IN ('scheduled', 'extra')),
      amount_minor INTEGER NOT NULL CHECK (amount_minor >= 0),
      savings_minor INTEGER NOT NULL DEFAULT 0 CHECK (savings_minor >= 0),
      period_start TEXT,
      period_end TEXT,
      received_on TEXT NOT NULL,
      note TEXT,
      created_at TEXT NOT NULL DEFAULT ${NOW},
      updated_at TEXT NOT NULL DEFAULT ${NOW},
      CHECK (kind = 'extra' OR (period_start IS NOT NULL AND period_end IS NOT NULL))
    )`,
    // One scheduled allowance per plan per period: generating twice is a no-op.
    `CREATE UNIQUE INDEX ux_allowances_plan_period
      ON allowances (plan_id, period_start) WHERE kind = 'scheduled'`,
    `CREATE INDEX ix_allowances_received ON allowances (received_on)`,

    `CREATE TABLE savings_transactions (
      id TEXT PRIMARY KEY NOT NULL,
      goal_id TEXT NOT NULL REFERENCES savings_goals(id) ON DELETE RESTRICT,
      kind TEXT NOT NULL CHECK (kind IN ('deposit', 'withdrawal')),
      source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'allowance', 'initial')),
      amount_minor INTEGER NOT NULL CHECK (amount_minor > 0),
      occurred_on TEXT NOT NULL,
      note TEXT,
      allowance_id TEXT REFERENCES allowances(id) ON DELETE SET NULL,
      created_at TEXT NOT NULL DEFAULT ${NOW},
      updated_at TEXT NOT NULL DEFAULT ${NOW}
    )`,
    `CREATE INDEX ix_savings_tx_goal ON savings_transactions (goal_id, occurred_on)`,
    `CREATE INDEX ix_savings_tx_date ON savings_transactions (occurred_on)`,
    `CREATE UNIQUE INDEX ux_savings_tx_allowance
      ON savings_transactions (allowance_id) WHERE allowance_id IS NOT NULL`,

    `CREATE TABLE expense_categories (
      id TEXT PRIMARY KEY NOT NULL,
      name TEXT NOT NULL CHECK (length(trim(name)) > 0),
      icon TEXT NOT NULL DEFAULT 'circle',
      is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
      sort_order INTEGER NOT NULL DEFAULT 0,
      archived_at TEXT,
      created_at TEXT NOT NULL DEFAULT ${NOW},
      updated_at TEXT NOT NULL DEFAULT ${NOW}
    )`,
    `CREATE UNIQUE INDEX ux_expense_categories_name
      ON expense_categories (name COLLATE NOCASE) WHERE archived_at IS NULL`,

    `CREATE TABLE expenses (
      id TEXT PRIMARY KEY NOT NULL,
      category_id TEXT NOT NULL REFERENCES expense_categories(id) ON DELETE RESTRICT,
      amount_minor INTEGER NOT NULL CHECK (amount_minor > 0),
      description TEXT,
      spent_on TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT ${NOW},
      updated_at TEXT NOT NULL DEFAULT ${NOW}
    )`,
    `CREATE INDEX ix_expenses_spent_on ON expenses (spent_on)`,
    `CREATE INDEX ix_expenses_category ON expenses (category_id, spent_on)`,

    `INSERT INTO expense_categories (id, name, icon, is_default, sort_order) VALUES
      ('cat-food', 'Food', 'food', 1, 10),
      ('cat-transport', 'Transportation', 'transport', 1, 20),
      ('cat-school', 'School', 'school', 1, 30),
      ('cat-printing', 'Printing', 'printing', 1, 40),
      ('cat-projects', 'Projects', 'projects', 1, 50),
      ('cat-supplies', 'Supplies', 'supplies', 1, 60),
      ('cat-mobile', 'Mobile Load/Data', 'mobile', 1, 70),
      ('cat-entertainment', 'Entertainment', 'entertainment', 1, 80),
      ('cat-personal', 'Personal', 'personal', 1, 90),
      ('cat-other', 'Other', 'other', 1, 100)`,
  ],
}
